name_size_max: 45
email_length: 45
password_min: 6
content_size_max: 250
rows: 5
users:
  per_page: 10
document:
  limit: 8
per_page: 10
categories:
  per_page: 10
image: "image1.png"
format_date: "%d-%m-%Y"
