name_size_max: 45
email_length: 45
password_min: 6
content_size_max: 250
rows: 5
users:
  per_page: 10
document:
  limit: 8
  limit_1: 4
per_page: 10
document_per_page: 5
categories:
  per_page: 10
image: "image1.png"
image_1: "doctor.png"
image_2: "background.jpg"
format_date: "%d-%m-%Y"
number_one: 1
number_seven: 7
number_seven_1: 518400
number_seven_2: 2505600
format_date: "%Y-%m-%d"
format_date_show: "%d-%m-%Y"
time_delay: 2
coin_down: 10
coin_free: 0
coin_up: 1
priority: 1
buycoins:
  per_page: 5
count_free_download: 3
coin_when_free: 0
coin_when_nonfree: 10
doc_per_page_1: 2
